export const RegionConstants = {
  FETCH_REGIONS: 'FETCH_REGIONS',
  FETCH_REGIONS_SUCCESS: 'FETCH_REGIONS_SUCCESS',
  FETCH_REGIONS_FAILURE: 'FETCH_REGIONS_FAILURE',

  FETCH_ACTIVE_REGIONS_REQUEST: ' FETCH_ACTIVE_REGIONS_REQUEST',
  FETCH_ACTIVE_REGIONS_SUCESS: 'FETCH_ACTIVE_REGIONS_SUCESS',
  FETCH_ACTIVE_REGIONS_FAILURE: 'FETCH_ACTIVE_REGIONS_FAILURE',
  FETCH_ALL_DATA: 'FETCH_REFRESH_DATA',

  FETCH_REGIONS_BY_PARAM_REQUEST: 'FETCH_REGIONS_BY_PARAM_REQUEST',
  FETCH_REGIONS_BY_PARAM_SUCCESS: 'FETCH_REGIONS_BY_PARAM_SUCCESS',
  FETCH_REGIONS_BY_PARAM_FAILURE: 'FETCH_REGIONS_BY_PARAM_FAILURE',

  FETCH_REGIONS_BY_QUERY_PARAM_REQUEST: 'FETCH_REGIONS_BY_QUERY_PARAM_REQUEST',
  FETCH_REGIONS_BY_QUERY_PARAM_SUCCESS: 'FETCH_REGIONS_BY_QUERY_PARAM_SUCCESS',
  FETCH_REGIONS_BY_QUERY_PARAM_FAILURE: 'FETCH_REGIONS_BY_QUERY_PARAM_FAILURE',

  FETCH_NEXT_PAGE_DATA_REQUEST: 'FETCH_NEXT_PAGE_DATA_REQUEST',
  FETCH_NEXT_PAGE_DATA_SUCCESS: 'FETCH_NEXT_PAGE_DATA_SUCCESS',
  FETCH_NEXT_PAGE_DATA_FAILURE: 'FETCH_NEXT_PAGE_DATA_FAILURE',

  FETCH_EMPTY_DATA: 'FETCH_EMPTY_DATA',

  FETCH_USERS_REQUEST: 'FETCH_USERS_REQUEST',
  FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESSS',
  FETCH_USERS_FAILURE: 'FETCH_USERS_FAILURE',

  FETCH_PDVS_REQUEST: 'FETCH_PDV_REQUEST',
  FETCH_PDVS_SUCCESS: 'FETCH_PDVS_SUCCESS',
  FETCH_PDVS_FAILURE: 'FETCH_PDVS_FAILURE',

  FETCH_STATES_REQUEST: 'FETCH_STATES_REQUEST',
  FETCH_STATES_SUCCESS: 'FETCH_STATES_SUCCESS',
  FETCH_STATES_FAILURE: 'FETCH_STATES_FAILURE',

  FETCH_CITIES_REQUEST: 'FETCH_CITIES_REQUEST',
  FETCH_CITIES_SUCCESS: 'FETCH_CITIES_SUCCESS',
  FETCH_CITIES_FAILURE: 'FETCH_CITIES_FAILURE',

  FETCH_SUBLOCALITIES_REQUEST: 'FETCH_SUBLOCALITIES_REQUEST',
  FETCH_SUBLOCALITIES_SUCCESS: 'FETCH_SUBLOCALITIES_SUCCESS',
  FETCH_SUBLOCALITIES_FAILURE: 'FETCH_SUBLOCALITIES_FAILURE',

  ADD_APPLY_FILTER_REQUEST: 'ADD_APPLY_FILTER_REQUEST',
  REGIONS_REMOVE_ALL_FILTERS: 'REGIONS_REMOVE_ALL_FILTERS',
  REGIONS_REMOVE_ITEM: 'REGIONS_REMOVE_ITEM',
  SHOW_MESSAGE: 'SHOW_MESSAGE',

  ADD_DATA_ON_RESULTS: 'ADD_DATA_ON_RESULTS',

  FETCH_USERS_BY_FILTER_REQUEST: 'FETCH_USERS_BY_FILTER_REQUEST',
  FETCH_USERS_BY_FILTER_SUCCESS: 'FETCH_USERS_BY_FILTER_SUCCESS',
  FETCH_USERS_BY_FILTER_FAILURE: 'FETCH_USERS_BY_FILTER_FAILURE',

  FETCH_PDV_BY_FILTER_REQUEST: 'FETCH_PDV_BY_FILTER_REQUEST',
  FETCH_PDV_BY_FILTER_SUCCESS: 'FETCH_PDV_BY_FILTER_SUCCESS',
  FETCH_PDV_BY_FILTER_FAILURE: 'FETCH_PDV_BY_FILTER_FAILURE',

  FETCH_STATE_BY_FILTER_REQUEST: 'FETCH_STATE_BY_FILTER_REQUEST',
  FETCH_STATE_BY_FILTER_SUCCESS: 'FETCH_STATE_BY_FILTER_SUCCESS',
  FETCH_STATE_BY_FILTLER_FAILURE: 'FETCH_STATE_BY_FILTER_FAILURE',

  FETCH_CITY_BY_FILTER_REQUEST: 'FETCH_CITY_BY_FILTER_REQUEST',
  FETCH_CITY_BY_FILTER_SUCCESS: 'FETCH_CITY_BY_FILTER_SUCCESS',
  FETCH_CITY_BY_FILTER_FAILURE: 'FETCH_CITY_BY_FILTER_FAILUERE',

  FETCH_NEIGHBORHOOD_BY_FILTER_REQUEST: 'FETCH_NEIGHBORHOOD_BY_FILTER_REQUEST',
  FETCH_NEIGHBORHOOD_BY_FILTER_SUCCESS: 'FETCH_NEIGHBORHOOD_BY_FILTER_SUCCESS',
  FETCH_NEIGHBORHOOD_BY_FILTER_FAILURE: 'FETCH_NEIGHBORHOOD_BY_FILTER_FAILURE',

  REGIONS_OPEN_STATUS_BAR: 'REGIONS_OPEN_STATUS_BAR',
  REGIONS_CLOSE_STATUS_BAR: 'REGIONS_CLOSE_STATUS_BAR',
  FETCH_NEXT_PAGE: 'FETCH_NEXT_PAGE',

  UPDATE_FILTER_DATA: 'UPDATE_FILTER_DATA',
}
