export const DISTRIBUTION_TYPES = {
  FETCH_ALL_DISTRIBUTION_REQUEST: 'FETCH_ALL_DISTRIBUTION_REQUEST',
  FETCH_ALL_DISTRIBUTION_SUCCESS: 'FETCH_ALL_DISTRIBUTION_SUCCESS',
  FETCH_ALL_DISTRIBUTION_FAILURE: 'FETCH_ALL_DISTRIBUTION_FAILURE',

  // Fetch distribution by column
  FETCH_DISTRIBUTION_BY_PARAM_REQUEST: 'FETCH_DISTRIBUTION_BY_PARAM_REQUEST',
  FETCH_DISTRIBUTION_BY_PARAM_SUCESS: 'FETCH_DISTRIBUTION_BY_PARAM_SUCESS',
  FETCH_DISTRIBUTION_BY_PARAM_FAILURE: 'FETCH_DISTRIBUTION_BY_PARAM_FAILURE',

  // Fetch register by search
  FETCH_DISTRIBUTION_BY_SEARCH_REQUEST: 'FETCH_DISTRIBUTION_BY_SEARCH_REQUEST',
  FETCH_DISTRIBUTION_BY_SEARCH_SUCCESS: 'FETCH_DISTRIBUTION_BY_SEARCH_SUCCESS',
  FETCH_DISTRIBUTION_BY_SEARCH_FAILURE: 'FETCH_DISTRIBUTION_BY_SEARCH_FAILURE',

  DISTRIBUTION_CENTER_ADD_FILTER_REQUEST:
    'DISTRIBUTION_CENTER_ADD_FILTER_REQUESTADD_FILTER_REQUEST',

  // FETCH_BY_FITLTER
  FETCH_ACTIVE_DISTRIBUTION_CENTER_REQUEST:
    'FETCH_ACTIVE_DISTRIBUTION_CENTER_REQUEST',
  FETCH_ACTIVE_DISTRIBUTION_CENTER_SUCCESS:
    'FETCH_ACTIVE_DISTRIBUTION_CENTER_SUCCESS',
  FETCH_ACTIVE_DISTRIBUTION_CENTER_FAILURE:
    'FETCH_ACTIVE_DISTRIBUTION_CENTER_FAILURE',

  FETCH_PARTICULARITY_DISTRIBUTION_REQUEST:
    'FETCH_PARTICULARITY_DISTRIBUTION_REQUEST',
  FETCH_PARTICULARITY_DISTRIBUTION_SUCCESS:
    'FETCH_PARTICULARITY_DISTRIBUTION_SUCCESS',
  FETCH_PARTICULARITY_DISTRIBUTION_FAILURE:
    'FETCH_PARTICULARITY_DISTRIBUTION_FAILURE',

  FETCH_APPORTIONMENT_DISTRIBUTION_REQUEST:
    'FETCH_APPORTIONMENT_DISTRIBUTION_REQUEST',

  FETCH_APPORTIONMENT_DISTRIBUTION_SUCCESS:
    'FETCH_APPORTIONMENT_DISTRIBUTION_SUCCESS',

  FETCH_APPORTIONMENT_DISTRIBUTION_FAILURE:
    'FETCH_APPORTIONMENT_DISTRIBUTION_FAILURE',

  FETCH_DISTRIBUTION_BY_CITY_REQUEST: 'FETCH_DISTRIBUTION_BY_CITY_REQUEST',
  FETCH_DISTRIBUTION_BY_CITY_SUCCESS: 'FETCH_DISTRIBUTION_BY_CITY_SUCCESS',
  FETCH_DISTRIBUTION_BY_CITY_FAILURE: 'FETCH_DISTRIBUTION_BY_CITY_FAILURE',

  FETCH_DISTRIBUTION_BY_STATE_REQUEST: 'FETCH_DISTRIBUTION_BY_STATE_REQUEST',
  FETCH_DISTRIBUTION_BY_STATE_SUCCESS: 'FETCH_DISTRIBUTION_BY_STATE_SUCCESS',
  FETCH_DISTRIBUTION_BY_STATE_FAILURE: 'FETCH_DISTRIBUTION_BY_STATE_FAILURE',

  FETCH_DISTRIBUTION_BY_FLAG_REQUEST: 'FETCH_DISTRIBUTION_BY_FLAG_REQUEST',
  FETCH_DISTRIBUTION_BY_FLAG_SUCCESS: 'FETCH_DISTRIBUTION_BY_FLAG_SUCCESS',
  FETCH_DISTRIBUTION_BY_FLAG_FAILURE: 'FETCH_DISTRIBUTION_BY_FLAG_FAILURE',

  DISTRIBUTION_CENTER_REMOVE_ALL_FILTER:
    'DISTRIBUTION_CENTER_REMOVE_ALL_FILTER',

  DISTRIBUTION_CENTER_REMOVE_FILTER: 'DISTRIBUTION_CENTER_REMOVE_FILTER',

  FETCH_HISTORY_APPORTIONMENT_REQUEST: 'FETCH_HISTORY_APPORTIONMENT_REQUEST',
  FETCH_HISTORY_APPORTIONMENT_SUCESSS: 'FETCH_HISTORY_APPORTIONMENT_SUCESSS',
  FETCH_HISTORY_APPORTIONMENT_FAILURE: 'FETCH_HISTORY_APPORTIONMENT_FAILURE',

  FETCH_HISTORY_BY_PARAM_REQUEST: 'FETCH_HISTORY_BY_PARAM_REQUEST',
  FETCH_HISTORY_BY_PARAM_SUCCESS: 'FETCH_HISTORY_BY_PARAM_SUCCESS',
  FETCH_HISTORY_BY_PARAM_FAILURE: 'FETCH_HISTORY_BY_PARAM_FAILURE',

  FETCH_HISTORY_PARTICULARY_REQUEST: 'FETCH_HISTORY_PARTICULARY_REQUEST',
  FETCH_HISTORY_PARTICULARY_SUCCESS: 'FETCH_HISTORY_PARTICULARY_SUCCESS',
  FETCH_HISTORY_PARTICULARY_FAILURE: 'FETCH_HISTORY_PARTICULARY_FAILURE',

  DISTRIBUTION_MODAL_ADD_FILTER: 'DISTRIBUTION_MODAL_ADD_FILTER',
  DISTRIBUTION_MODAL_REMOVE_ALL_FILTERS:
    'DISTRIBUTION_MODAL_REMOVE_ALL_FILTERS',

  FETCTH_HISTORY_BY_Q_PARAM_REQUEST: 'FETCTH_HISTORY_BY_Q_PARAM_REQUEST',
  FETCH_HISTORY_BY_Q_PARAM_SUCCESS: 'FETCH_HISTORY_BY_Q_PARAM_SUCCESS',
  FETCH_HISTORY_BY_Q_PARAM_FAILURE: 'FETCH_HISTORY_BY_Q_PARAM_FAILURE',

  REMOVE_DISTRIBUTION_MODAL_ITEM: 'REMOVE_DISTRIBUTION_MODAL_ITEM',
}
