export const TypologyTypes = {
  FETCH_TYPOLOGY_REQUEST: 'FETCH_TYPOLOGY',
  FETCH_TYPOLOGY_SUCESS: 'FETCH_TYPOLOGY_SUCESS',
  FETCH_TYPOLOGY_FAILURE: 'FETCH_TYPOLOGY_FAILURE',

  FETCH_ACTIVE_TYPOLOGY_REQUEST: ' FETCH_ACTIVE_TYPOLOGY_REQUEST',
  FETCH_ACTIVE_TYPOLOGY_SUCESS: 'FETCH_ACTIVE_TYPOLOGY_SUCESS',
  FETCH_ACTIVE_TYPOLOGY_FAILURE: 'FETCH_ACTIVE_TYPOLOGY_FAILURE',
  FETCH_ALL_DATA: 'FETCH_REFRESH_DATA',

  FETCH_TYPOLOGY_BY_PARAM_REQUEST: 'FETCH_TYPOLOGY_BY_PARAM_REQUEST',
  FETCH_TYPOLOGY_BY_PARAM_SUCCESS: 'FETCH_TYPOLOGY_BY_PARAM_SUCCESS',
  FETCH_TYPOLOGY_BY_PARAM_FAILURE: 'FETCH_TYPOLOGY_BY_PARAM_FAILURE',

  FETCH_TYPOLOGY_BY_QUERY_PARAM_REQUEST:
    'FETCH_TYPOLOGY_BY_QUERY_PARAM_REQUEST',
  FETCH_TYPOLOGY_BY_QUERY_PARAM_SUCCESS:
    'FETCH_TYPOLOGY_BY_QUERY_PARAM_SUCCESS',
  FETCH_TYPOLOGY_BY_QUERY_PARAM_FAILURE:
    'FETCH_TYPOLOGY_BY_QUERY_PARAM_FAILURE',

  ADD_TYPOLOGY_FITER: 'ADD_TYPOLOGY_FITER',
  REMOVE_ALL_FILTERS: 'REMOVE_ALL_FILTERS',
  REMOVE_ITEM: 'REMOVE_ITEM',

  OPEN_APPLY_FILTER_MENU: 'OPEN_APPLY_FILTER_MENU',
}
