export const AuthorizationsConstants = {
    FETCH_AUTHORIZATIONS: "FETCH_AUTHORIZATIONS",
    FETCH_AUTHORIZATIONS_SUCCESS: "FETCH_AUTHORIZATIONS_SUCCESS",
    FETCH_AUTHORIZATIONS_FAILURE: "FETCH_AUTHORIZATIONS_FAILURE",

    TOTALS_AUTHORIZATIONS: "TOTALS_AUTHORIZATIONS",
    TOTALS_AUTHORIZATIONS_RESET: "TOTALS_AUTHORIZATIONS_RESET",
    TOTALS_AUTHORIZATIONS_SUCCESS: "TOTALS_AUTHORIZATIONS_SUCCESS",
    TOTALS_AUTHORIZATIONS_FAILURE: "TOTALS_AUTHORIZATIONS_FAILURE",
};
