export const CalendarLinksConstants = {
    FETCH_CALENDAR_LINKS: "FETCH_CALENDAR_LINKS",
    FETCH_CALENDAR_LINKS_SUCCESS: "FETCH_CALENDAR_LINKS_SUCCESS",
    FETCH_CALENDAR_LINKS_FAILURE: "FETCH_CALENDAR_LINKS_FAILURE",

    GET_CALENDAR_LINKS: "GET_CALENDAR_LINKS",
    GET_CALENDAR_LINKS_SUCCESS: "GET_CALENDAR_LINKS_SUCCESS",
    GET_CALENDAR_LINKS_FAILURE: "GET_CALENDAR_LINKS_FAILURE",

    PUT_CALENDAR_LINKS: "PUT_CALENDAR_LINKS",
    PUT_CALENDAR_LINKS_SUCCESS: "PUT_CALENDAR_LINKS_SUCCESS",
    PUT_CALENDAR_LINKS_FAILURE: "PUT_CALENDAR_LINKS_FAILURE",

    POST_CALENDAR_LINKS: "POST_CALENDAR_LINKS",
    POST_CALENDAR_LINKS_SUCCESS: "POST_CALENDAR_LINKS_SUCCESS",
    POST_CALENDAR_LINKS_FAILURE: "POST_CALENDAR_LINKS_FAILURE",

    DELETE_CALENDAR_LINKS: "DELETE_CALENDAR_LINKS",
    DELETE_CALENDAR_LINKS_SUCCESS: "DELETE_CALENDAR_LINKS_SUCCESS",
    DELETE_CALENDAR_LINKS_FAILURE: "DELETE_CALENDAR_LINKS_FAILURE",
};