export default {
    FETCH_CALENDARS: "FETCH_CALENDARS",
    FETCH_CALENDARS_SUCCESS: "FETCH_CALENDARS_SUCCESS",
    FETCH_CALENDARS_FAILURE: "FETCH_CALENDARS_FAILURE",

    GET_CALENDAR: "GET_CALENDAR",
    GET_CALENDAR_SUCCESS: "GET_CALENDAR_SUCCESS",
    GET_CALENDAR_FAILURE: "GET_CALENDAR_FAILURE",

    PUT_CALENDAR: "PUT_CALENDAR",
    PUT_CALENDAR_SUCCESS: "PUT_CALENDAR_SUCCESS",
    PUT_CALENDAR_FAILURE: "PUT_CALENDAR_FAILURE",

    POST_CALENDAR: "POST_CALENDAR",
    POST_CALENDAR_SUCCESS: "POST_CALENDAR_SUCCESS",
    POST_CALENDAR_FAILURE: "POST_CALENDAR_FAILURE",

    DELETE_CALENDAR: "DELETE_CALENDAR",
    DELETE_CALENDAR_SUCCESS: "DELETE_CALENDAR_SUCCESS",
    DELETE_CALENDAR_FAILURE: "DELETE_CALENDAR_FAILURE",
};