export default {
    FETCH_CALENDAR_EVENTS: "FETCH_CALENDAR_EVENTS",
    FETCH_CALENDAR_EVENTS_SUCCESS: "FETCH_CALENDAR_EVENTS_SUCCESS",
    FETCH_CALENDAR_EVENTS_FAILURE: "FETCH_CALENDAR_EVENTS_FAILURE",

    GET_CALENDAR_EVENTS: "GET_CALENDAR_EVENTS",
    GET_CALENDAR_EVENTS_SUCCESS: "GET_CALENDAR_EVENTS_SUCCESS",
    GET_CALENDAR_EVENTS_FAILURE: "GET_CALENDAR_EVENTS_FAILURE",

    PUT_CALENDAR_EVENTS: "PUT_CALENDAR_EVENTS",
    PUT_CALENDAR_EVENTS_SUCCESS: "PUT_CALENDAR_EVENTS_SUCCESS",
    PUT_CALENDAR_EVENTS_FAILURE: "PUT_CALENDAR_EVENTS_FAILURE",

    POST_CALENDAR_EVENTS: "POST_CALENDAR_EVENTS",
    POST_CALENDAR_EVENTS_SUCCESS: "POST_CALENDAR_EVENTS_SUCCESS",
    POST_CALENDAR_EVENTS_FAILURE: "POST_CALENDAR_EVENTS_FAILURE",

    DELETE_CALENDAR_EVENTS: "DELETE_CALENDAR_EVENTS",
    DELETE_CALENDAR_EVENTS_SUCCESS: "DELETE_CALENDAR_EVENTS_SUCCESS",
    DELETE_CALENDAR_EVENTS_FAILURE: "DELETE_CALENDAR_EVENTS_FAILURE",
};