export default {
    GET_CLIENT: "GET_CLIENT",
    GET_CLIENT_SUCCESS: "GET_CLIENT_SUCCESS",
    GET_CLIENT_FAILURE: "GET_CLIENT_FAILURE",

    PUT_CLIENT: "PUT_CLIENT",
    PUT_CLIENT_SUCCESS: "PUT_CLIENT_SUCCESS",
    PUT_CLIENT_FAILURE: "PUT_CLIENT_FAILURE",
};
