export const ContractorsConstants = {
    FETCH_CONTRACTORS: 'FETCH_CONTRACTORS',
    FETCH_CONTRACTORS_SUCCESS: 'FETCH_CONTRACTORS_SUCCESS',
    FETCH_CONTRACTORS_FAILURE: 'FETCH_CONTRACTORS_FAILURE',

    GET_CONTRACTOR: 'GET_CONTRACTOR',
    GET_CONTRACTOR_SUCCESS: 'GET_CONTRACTOR_SUCCESS',
    GET_CONTRACTOR_FAILURE: 'GET_CONTRACTOR_FAILURE',

    POST_CONTRACTOR: 'POST_CONTRACTOR',
    POST_CONTRACTOR_SUCCESS: 'POST_CONTRACTOR_SUCCESS',
    POST_CONTRACTOR_FAILURE: 'POST_CONTRACTOR_FAILURE',

    PUT_CONTRACTOR: 'PUT_CONTRACTOR',
    PUT_CONTRACTOR_SUCCESS: 'PUT_CONTRACTOR_SUCCESS',
    PUT_CONTRACTOR_FAILURE: 'PUT_CONTRACTOR_FAILURE',

    GET_CONTRACTOR_GROUP: 'GET_CONTRACTOR_GROUP',
    GET_CONTRACTOR_GROUP_SUCCESS: 'GET_CONTRACTOR_GROUP_SUCCESS',
    GET_CONTRACTOR_GROUP_FAILURE: 'GET_CONTRACTOR_GROUP_FAILURE',

    FETCH_CONTRACTOR_GROUP: 'FETCH_CONTRACTOR_GROUP',
    FETCH_CONTRACTOR_GROUP_SUCCESS: 'FETCH_CONTRACTOR_GROUP_SUCCESS',
    FETCH_CONTRACTOR_GROUP_FAILURE: 'FETCH_CONTRACTOR_GROUP_FAILURE',

    POST_CONTRACTOR_GROUP: 'POST_CONTRACTOR_GROUP',
    POST_CONTRACTOR_GROUP_SUCCESS: 'POST_CONTRACTOR_GROUP_SUCCESS',
    POST_CONTRACTOR_GROUP_FAILURE: 'POST_CONTRACTOR_GROUP_FAILURE',

    PUT_CONTRACTOR_GROUP: 'PUT_CONTRACTOR_GROUP',
    PUT_CONTRACTOR_GROUP_SUCCESS: 'PUT_CONTRACTOR_GROUP_SUCCESS',
    PUT_CONTRACTOR_GROUP_FAILURE: 'PUT_CONTRACTOR_GROUP_FAILURE',

    DELETE_CONTRACTOR_GROUP: 'DELETE_CONTRACTOR_GROUP',
    DELETE_CONTRACTOR_GROUP_SUCCESS: 'DELETE_CONTRACTOR_GROUP_SUCCESS',
    DELETE_CONTRACTOR_GROUP_FAILURE: 'DELETE_CONTRACTOR_GROUP_FAILURE',

    FETCH_CONTRACTOR_SUB: 'FETCH_CONTRACTOR_SUB',
    FETCH_CONTRACTOR_SUB_SUCCESS: 'FETCH_CONTRACTOR_SUB_SUCCESS',
    FETCH_CONTRACTOR_SUB_FAILURE: 'FETCH_CONTRACTOR_SUB_FAILURE'
}
