export const EPIDistribuitonsConstants = {
  ADD_EPI_DRAFT_DISTRIBUTIONS: 'ADD_EPI_DRAFT_DISTRIBUTIONS',
  ADD_EPI_DRAFT_DISTRIBUTIONS_SUCCESS: 'ADD_EPI_DRAFT_DISTRIBUTIONS_SUCCESS',
  ADD_EPI_DRAFT_DISTRIBUTIONS_FAILURE: 'ADD_EPI_DRAFT_DISTRIBUTIONS_FAILURE',

  UPDATE_EPI_DRAFT_DISTRIBUTIONS: 'UPDATE_EPI_DRAFT_DISTRIBUTIONS',
  UPDATE_EPI_DRAFT_DISTRIBUTIONS_SUCCESS:
    'UPDATE_EPI_DRAFT_DISTRIBUTIONS_SUCCESS',
  UPDATE_EPI_DRAFT_DISTRIBUTIONS_FAILURE:
    'UPDATE_EPI_DRAFT_DISTRIBUTIONS_FAILURE',

  VIEW_EPI_DRAFT_DISTRIBUTIONS: 'VIEW_EPI_DRAFT_DISTRIBUTIONS',
  VIEW_EPI_DRAFT_DISTRIBUTIONS_SUCCESS: 'VIEW_EPI_DRAFT_DISTRIBUTIONS_SUCCESS',
  VIEW_EPI_DRAFT_DISTRIBUTIONS_FAILURE: 'VIEW_EPI_DRAFT_DISTRIBUTIONS_FAILURE',

  DRAFT_MISSING_EPIS: 'DRAFT_MISSING_EPIS',
  DRAFT_MISSING_EPIS_SUCCESS: 'DRAFT_MISSING_EPIS_SUCCESS',
  DRAFT_MISSING_EPIS_FAILURE: 'DRAFT_MISSING_EPIS_FAILURE',
}
