export const EPIWarehouseConstants = {
  FETCH_EPIWAREHOUSE: 'FETCH_EPIWAREHOUSE',
  FETCH_EPIWAREHOUSE_SUCCESS: 'FETCH_EPIWAREHOUSE_SUCCESS',
  FETCH_EPIWAREHOUSE_FAILURE: 'FETCH_EPIWAREHOUSE_FAILURE',

  GET_EPIWAREHOUSE: 'GET_EPIWAREHOUSE',
  GET_EPIWAREHOUSE_SUCCESS: 'GET_EPIWAREHOUSE_SUCCESS',
  GET_EPIWAREHOUSE_FAILURE: 'GET_EPIWAREHOUSE_FAILURE',

  ADD_EPITYPE: 'ADD_EPITYPE',
  ADD_EPITYPE_SUCCESS: 'ADD_EPITYPE_SUCCESS',
  ADD_EPITYPE_FAILURE: 'ADD_EPITYPE_FAILURE',

  GET_DECREASE: 'GET_DECREASE',
  GET_DECREASE_SUCCESS: 'GET_DECREASE_SUCCESS',
  GET_DECREASE_FAILURE: 'GET_DECREASE_FAILURE',

  EPI_INVENTORY_MANUAL_DECREASE_ADD: 'EPI_INVENTORY_MANUAL_DECREASE_ADD',
  EPI_INVENTORY_MANUAL_DECREASE_ADD_SUCCESS:
    'EPI_INVENTORY_MANUAL_DECREASE_ADD_SUCCESS',
  EPI_INVENTORY_MANUAL_DECREASE_ADD_FAILURE:
    'EPI_INVENTORY_MANUAL_DECREASE_ADD_FAILURE',

  FETCH_EPI_FISCAL_NOTES: 'FETCH_EPI_FISCAL_NOTES',
  FETCH_EPI_FISCAL_NOTES_SUCCESS: 'FETCH_EPI_FISCAL_NOTES_SUCCESS',
  FETCH_EPI_FISCAL_NOTES_FAILURE: 'FETCH_EPI_FISCAL_NOTES_FAILURE',

  FETCH_EPIS_TYPES: 'FETCH_EPIS_TYPES',
  FETCH_EPIS_TYPES_SUCCESS: 'FETCH_EPIS_TYPES_SUCCESS',
  FETCH_EPIS_TYPES_FAILURE: 'FETCH_EPIS_TYPES_FAILURE',

  ADD_EPIS_TRADE: 'ADD_EPIS_TRADE',
  ADD_EPIS_TRADE_SUCCESS: 'ADD_EPIS_TRADE_SUCCESS',
  ADD_EPIS_TRADE_FAILURE: 'ADD_EPIS_TRADE_FAILURE',

  FETCH_EPIS_TYPES: 'FETCH_EPIS',
  FETCH_EPIS_TYPES_SUCCESS: 'FETCH_EPIS_SUCCESS',
  FETCH_EPIS_TYPES_FAILURE: 'FETCH_EPIS_FAILURE',

  UPDATE_EPITYPE_SIZES: 'UPDATE_EPITYPE_SIZES',
  UPDATE_EPITYPE_SIZES_SUCCESS: 'UPDATE_EPITYPE_SIZES_SUCCESS',
  UPDATE_EPITYPE_SIZES_FAILURE: 'UPDATE_EPITYPE_SIZES_FAILURE',

  ADD_EPI_FISCAL_NOTE: 'ADD_EPI_FISCAL_NOTE',
  ADD_EPI_FISCAL_NOTE_SUCCESS: 'ADD_EPI_FISCAL_NOTE_SUCCESS',
  ADD_EPI_FISCAL_NOTE_FAILURE: 'ADD_EPI_FISCAL_NOTE_FAILURE',

  DELETE_FISCAL_NOTE: 'DELETE_FISCAL_NOTE',
  DELETE_FISCAL_NOTE_SUCCESS: 'DELETE_FISCAL_NOTE_SUCCESS',
  DELETE_FISCAL_NOTE_FAILURE: 'DELETE_FISCAL_NOTE_FAILURE',

  FILTER_PURCHASE_DATE: 'FILTER_PURCHASE_DATE',
  FILTER_PURCHASE_DATE_SUCCESS: 'FILTER_PURCHASE_DATE_SUCCESS',
  FILTER_PURCHASE_DATE_FAILURE: 'FILTER_PURCHASE_DATE_FAILURE',

  FETCH_FISCAL_NOTE_BY_ID: 'FETCH_FISCAL_NOTE_BY_ID',
  FETCH_FISCAL_NOTE_BY_ID_SUCCESS: 'FETCH_FISCAL_NOTE_BY_ID_SUCCESS',
  FETCH_FISCAL_NOTE_BY_ID_FAILURE: 'FETCH_FISCAL_NOTE_BY_ID_FAILURE',

  FETCH_EPI_QUANTITY: 'FETCH_EPI_QUANTITY',
  FETCH_EPI_QUANTITY_SUCCESS: 'FETCH_EPI_QUANTITY_SUCCESS',
  FETCH_EPI_QUANTITY_FAILURE: 'FETCH_EPI_QUANTITY_FAILURE',
}

export const EPICheckNameConstants = {
  CHECK_NAME: 'EPI_CHECK_NAME',
  CHECK_NAME_SUCCESS: 'EPI_CHECK_NAME_SUCCESS',
  CHECK_NAME_FAILURE: 'EPI_CHECK_NAME_FAILURE',

  UPDATE_EPI: 'UPDATE_EPI',
  UPDATE_EPI_SUCCESS: 'UPDATE_EPI_SUCCESS',
  UPDATE_EPI_FAILURE: 'UPDATE_EPI_FAILURE',

  DELETE_EPI: 'DELETE_EPI',
  DELETE_EPI_SUCCESS: 'DELETE_EPI_SUCCESS',
  DELETE_EPI_FAILURE: 'DELETE_EPI_FAILURE',
}
