export const HierarchiesElementsConstants = {
    FETCH_HIERARCHIES_ELEMENTS: "FETCH_HIERARCHIES_ELEMENTS",
    FETCH_HIERARCHIES_ELEMENTS_SUCCESS: "FETCH_HIERARCHIES_ELEMENTS_SUCCESS",
    FETCH_HIERARCHIES_ELEMENTS_FAILURE: "FETCH_HIERARCHIES_ELEMENTS_FAILURE",

    GET_HIERARCHIES_ELEMENT: "GET_HIERARCHIES_ELEMENT",
    GET_HIERARCHIES_ELEMENT_SUCCESS: "GET_HIERARCHIES_ELEMENT_SUCCESS",
    GET_HIERARCHIES_ELEMENT_FAILURE: "GET_HIERARCHIES_ELEMENT_FAILURE",

    PUT_HIERARCHIES_ELEMENT: "PUT_HIERARCHIES_ELEMENT",
    PUT_HIERARCHIES_ELEMENT_SUCCESS: "PUT_HIERARCHIES_ELEMENT_SUCCESS",
    PUT_HIERARCHIES_ELEMENT_FAILURE: "PUT_HIERARCHIES_ELEMENT_FAILURE",

    POST_HIERARCHIES_ELEMENT: "POST_HIERARCHIES_ELEMENT",
    POST_HIERARCHIES_ELEMENT_SUCCESS: "POST_HIERARCHIES_ELEMENT_SUCCESS",
    POST_HIERARCHIES_ELEMENT_FAILURE: "POST_HIERARCHIES_ELEMENT_FAILURE",

    DELETE_HIERARCHIES_ELEMENT: "DELETE_HIERARCHIES_ELEMENT",
    DELETE_HIERARCHIES_ELEMENT_SUCCESS: "DELETE_HIERARCHIES_ELEMENT_SUCCESS",
    DELETE_HIERARCHIES_ELEMENT_FAILURE: "DELETE_HIERARCHIES_ELEMENT_FAILURE",

    GET_HIERARCHIES_ELEMENT_PATH: "GET_HIERARCHIES_ELEMENT_PATH",
    GET_HIERARCHIES_ELEMENT_SUCCESS_PATH: "GET_HIERARCHIES_ELEMENT_SUCCESS_PATH",
    GET_HIERARCHIES_ELEMENT_FAILURE_PATH: "GET_HIERARCHIES_ELEMENT_FAILURE_PATH",

    GET_HIERARCHIES_ELEMENT_PEOPLE: "GET_HIERARCHIES_ELEMENT_PEOPLE",
    GET_HIERARCHIES_ELEMENT_PEOPLE_SUCCESS: "GET_HIERARCHIES_ELEMENT_PEOPLE_SUCCESS",
    GET_HIERARCHIES_ELEMENT_PEOPLE_FAILURE: "GET_HIERARCHIES_ELEMENT_PEOPLE_FAILURE",

    GET_HIERARCHIES_ELEMENT_STORES: "GET_HIERARCHIES_ELEMENT_STORES",
    GET_HIERARCHIES_ELEMENT_STORES_SUCCESS: "GET_HIERARCHIES_ELEMENT_STORES_SUCCESS",
    GET_HIERARCHIES_ELEMENT_STORES_FAILURE: "GET_HIERARCHIES_ELEMENT_STORES_FAILURE",

    POST_HIERARCHIES_ELEMENT_LINKS: "POST_HIERARCHIES_ELEMENT_LINKS",
    POST_HIERARCHIES_ELEMENT_LINKS_SUCCESS: "POST_HIERARCHIES_ELEMENT_LINKS_SUCCESS",
    POST_HIERARCHIES_ELEMENT_LINKS_FAILURE: "POST_HIERARCHIES_ELEMENT_LINKS_FAILURE",

    DELETE_HIERARCHIES_ELEMENT_LINKS: "DELETE_HIERARCHIES_ELEMENT_LINKS",
    DELETE_HIERARCHIES_ELEMENT_LINKS_SUCCESS: "DELETE_HIERARCHIES_ELEMENT_LINKS_SUCCESS",
    DELETE_HIERARCHIES_ELEMENT_LINKS_FAILURE: "DELETE_HIERARCHIES_ELEMENT_LINKS_FAILURE",
};
