export default {
    FETCH_HIERARCHY_LINKS: "FETCH_HIERARCHY_LINKS",
    FETCH_HIERARCHY_LINKS_SUCCESS: "FETCH_HIERARCHY_LINKS_SUCCESS",
    FETCH_HIERARCHY_LINKS_FAILURE: "FETCH_HIERARCHY_LINKS_FAILURE",

    GET_HIERARCHY_LINK: "GET_HIERARCHY_LINK",
    GET_HIERARCHY_LINK_SUCCESS: "GET_HIERARCHY_LINK_SUCCESS",
    GET_HIERARCHY_LINK_FAILURE: "GET_HIERARCHY_LINK_FAILURE",

    PUT_HIERARCHY_LINK: "PUT_HIERARCHY_LINK",
    PUT_HIERARCHY_LINK_SUCCESS: "PUT_HIERARCHY_LINK_SUCCESS",
    PUT_HIERARCHY_LINK_FAILURE: "PUT_HIERARCHY_LINK_FAILURE",

    POST_HIERARCHY_LINK: "POST_HIERARCHY_LINK",
    POST_HIERARCHY_LINK_SUCCESS: "POST_HIERARCHY_LINK_SUCCESS",
    POST_HIERARCHY_LINK_FAILURE: "POST_HIERARCHY_LINK_FAILURE",

    DELETE_HIERARCHY_LINK: "DELETE_HIERARCHY_LINK",
    DELETE_HIERARCHY_LINK_SUCCESS: "DELETE_HIERARCHY_LINK_SUCCESS",
    DELETE_HIERARCHY_LINK_FAILURE: "DELETE_HIERARCHY_LINK_FAILURE",
};