export const HierarchiesStructuresConstants = {
    FETCH_HIERARCHIES_STRUCTURES: "FETCH_HIERARCHIES_STRUCTURES",
    FETCH_HIERARCHIES_STRUCTURES_SUCCESS: "FETCH_HIERARCHIES_STRUCTURES_SUCCESS",
    FETCH_HIERARCHIES_STRUCTURES_FAILURE: "FETCH_HIERARCHIES_STRUCTURES_FAILURE",

    GET_HIERARCHIES_STRUCTURE: "GET_HIERARCHIES_STRUCTURE",
    GET_HIERARCHIES_STRUCTURE_SUCCESS: "GET_HIERARCHIES_STRUCTURE_SUCCESS",
    GET_HIERARCHIES_STRUCTURE_FAILURE: "GET_HIERARCHIES_STRUCTURE_FAILURE",

    PUT_HIERARCHIES_STRUCTURE: "PUT_HIERARCHIES_STRUCTURE",
    PUT_HIERARCHIES_STRUCTURE_SUCCESS: "PUT_HIERARCHIES_STRUCTURE_SUCCESS",
    PUT_HIERARCHIES_STRUCTURE_FAILURE: "PUT_HIERARCHIES_STRUCTURE_FAILURE",

    POST_HIERARCHIES_STRUCTURE: "POST_HIERARCHIES_STRUCTURE",
    POST_HIERARCHIES_STRUCTURE_SUCCESS: "POST_HIERARCHIES_STRUCTURE_SUCCESS",
    POST_HIERARCHIES_STRUCTURE_FAILURE: "POST_HIERARCHIES_STRUCTURE_FAILURE",

    DELETE_HIERARCHIES_STRUCTURE: "DELETE_HIERARCHIES_STRUCTURE",
    DELETE_HIERARCHIES_STRUCTURE_SUCCESS: "DELETE_HIERARCHIES_STRUCTURE_SUCCESS",
    DELETE_HIERARCHIES_STRUCTURE_FAILURE: "DELETE_HIERARCHIES_STRUCTURE_FAILURE",
};