const HierarchiesTreeConstants = {
  FETCH_HIERARCHIES_TREE: 'FETCH_HIERARCHIES_TREE',
  FETCH_HIERARCHIES_TREE_SUCCESS: 'FETCH_HIERARCHIES_TREE_SUCCESS',
  FETCH_HIERARCHIES_TREE_FAILURE: 'FETCH_HIERARCHIES_TREE_FAILURE',
}

export default HierarchiesTreeConstants
