export const HierarchiesConstants = {
    FETCH_HIERARCHIES: "FETCH_HIERARCHIES",
    FETCH_HIERARCHIES_SUCCESS: "FETCH_HIERARCHIES_SUCCESS",
    FETCH_HIERARCHIES_FAILURE: "FETCH_HIERARCHIES_FAILURE",

    GET_HIERARCHIES: "GET_HIERARCHIES",
    GET_HIERARCHIES_SUCCESS: "GET_HIERARCHIES_SUCCESS",
    GET_HIERARCHIES_FAILURE: "GET_HIERARCHIES_FAILURE",

    PUT_HIERARCHIES: "PUT_HIERARCHIES",
    PUT_HIERARCHIES_SUCCESS: "PUT_HIERARCHIES_SUCCESS",
    PUT_HIERARCHIES_FAILURE: "PUT_HIERARCHIES_FAILURE",

    POST_HIERARCHIES: "POST_HIERARCHIES",
    POST_HIERARCHIES_SUCCESS: "POST_HIERARCHIES_SUCCESS",
    POST_HIERARCHIES_FAILURE: "POST_HIERARCHIES_FAILURE",

    DELETE_HIERARCHIES: "DELETE_HIERARCHIES",
    DELETE_HIERARCHIES_SUCCESS: "DELETE_HIERARCHIES_SUCCESS",
    DELETE_HIERARCHIES_FAILURE: "DELETE_HIERARCHIES_FAILURE",

    GET_HIERARCHIES_PEOPLE: "GET_HIERARCHIES_PEOPLE",
    GET_HIERARCHIES_PEOPLE_SUCCESS: "GET_HIERARCHIES_PEOPLE_SUCCESS",
    GET_HIERARCHIES_PEOPLE_FAILURE: "GET_HIERARCHIES_PEOPLE_FAILURE",
};
