export const LocalizationsConstants = {
    FETCH_LOCALIZATIONS: "FETCH_LOCALIZATIONS",
    FETCH_LOCALIZATIONS_SUCCESS: "FETCH_LOCALIZATIONS_SUCCESS",
    FETCH_LOCALIZATIONS_FAILURE: "FETCH_LOCALIZATIONS_FAILURE",
};
