export const MarketsConstants = {
    FETCH_MARKETS: "FETCH_MARKETS",
    FETCH_MARKETS_SUCCESS: "FETCH_MARKETS_SUCCESS",
    FETCH_MARKETS_FAILURE: "FETCH_MARKETS_FAILURE",

    GET_MARKETS: "GET_MARKETS",
    GET_MARKETS_SUCCESS: "GET_MARKETS_SUCCESS",
    GET_MARKETS_FAILURE: "GET_MARKETS_FAILURE",
};
