export default
{
    FETCH_PEOPLES: "FETCH_PEOPLES",
    FETCH_PEOPLES_SUCCESS: "FETCH_PEOPLES_SUCCESS",
    FETCH_PEOPLES_FAILURE: "FETCH_PEOPLES_FAILURE",

    FIND_PEOPLES: "FIND_PEOPLES",
    FIND_PEOPLES_SUCCESS: "FIND_PEOPLES_SUCCESS",
    FIND_PEOPLES_FAILURE: "FIND_PEOPLES_FAILURE",

    GET_PEOPLES: "GET_PEOPLES",
    GET_PEOPLES_SUCCESS: "GET_PEOPLES_SUCCESS",
    GET_PEOPLES_FAILURE: "GET_PEOPLES_FAILURE",

    PUT_PEOPLES: "PUT_PEOPLES",
    PUT_PEOPLES_SUCCESS: "PUT_PEOPLES_SUCCESS",
    PUT_PEOPLES_FAILURE: "PUT_PEOPLES_FAILURE",

    POST_PEOPLES: "POST_PEOPLES",
    POST_PEOPLES_SUCCESS: "POST_PEOPLES_SUCCESS",
    POST_PEOPLES_FAILURE: "POST_PEOPLES_FAILURE",

    DELETE_PEOPLES: "DELETE_PEOPLES",
    DELETE_PEOPLES_SUCCESS: "DELETE_PEOPLES_SUCCESS",
    DELETE_PEOPLES_FAILURE: "DELETE_PEOPLES_FAILURE",

    WITHOUT_ROUTE_PEOPLES: "WITHOUT_ROUTE_PEOPLES",
    WITHOUT_ROUTE_PEOPLES_SUCCESS: "WITHOUT_ROUTE_PEOPLES_SUCCESS",
    WITHOUT_ROUTE_PEOPLES_FAILURE: "WITHOUT_ROUTE_PEOPLES_FAILURE"
}
