export default
{
    FETCH_CONTRACTORS: 'FETCH_CONTRACTORS',
    FETCH_CONTRACTORS_SUCCESS: 'FETCH_CONTRACTORS_SUCCESS',
    FETCH_CONTRACTORS_FAILURE: 'FETCH_CONTRACTORS_FAILURE',

    GET_CONTRACTOR: 'GET_CONTRACTOR',
    GET_CONTRACTOR_SUCCESS: 'GET_CONTRACTOR_SUCCESS',
    GET_CONTRACTOR_FAILURE: 'GET_CONTRACTOR_FAILURE',
}