export const ProfilesConstants = {
    FETCH_PROFILES: "FETCH_PROFILES",
    FETCH_PROFILES_SUCCESS: "FETCH_PROFILES_SUCCESS",
    FETCH_PROFILES_FAILURE: "FETCH_PROFILES_FAILURE",

    GET_PROFILES: "GET_PROFILES",
    GET_PROFILES_SUCCESS: "GET_PROFILES_SUCCESS",
    GET_PROFILES_FAILURE: "GET_PROFILES_FAILURE",

    PUT_PROFILES: "PUT_PROFILES",
    PUT_PROFILES_SUCCESS: "PUT_PROFILES_SUCCESS",
    PUT_PROFILES_FAILURE: "PUT_PROFILES_FAILURE",

    POST_PROFILES: "POST_PROFILES",
    POST_PROFILES_SUCCESS: "POST_PROFILES_SUCCESS",
    POST_PROFILES_FAILURE: "POST_PROFILES_FAILURE",

    DELETE_PROFILES: "DELETE_PROFILES",
    DELETE_PROFILES_SUCCESS: "DELETE_PROFILES_SUCCESS",
    DELETE_PROFILES_FAILURE: "DELETE_PROFILES_FAILURE",

    USER_PROFILE: "USER_PROFILE",
    USER_PROFILE_SUCCESS: "USER_PROFILE_SUCCESS",
    USER_PROFILE_FAILURE: "USER_PROFILES_FAILURE",

};
