export const RegionConstants = {
    FETCH_REGION: "FETCH_REGION",
    FETCH_REGION_SUCCESS: "FETCH_REGION_SUCCESS",
    FETCH_REGION_FAILURE: "FETCH_REGION_FAILURE",

    GET_REGION: "GET_REGION",
    GET_REGION_SUCCESS: "GET_REGION_SUCCESS",
    GET_REGION_FAILURE: "GET_REGION_FAILURE",
};
