export const RegionsConstants = {
    FETCH_REGIONS: "FETCH_REGIONS",
    FETCH_REGIONS_SUCCESS: "FETCH_REGIONS_SUCCESS",
    FETCH_REGIONS_FAILURE: "FETCH_REGIONS_FAILURE",

    FETCH_REGIONS_LINKS: "FETCH_REGIONS_LINKS",
    FETCH_REGIONS_LINKS_SUCCESS: "FETCH_REGIONS_LINKS_SUCCESS",
    FETCH_REGIONS_LINKS_FAILURE: "FETCH_REGIONS_LINKS_FAILURE",

    GET_REGIONS: "GET_REGIONS",
    GET_REGIONS_SUCCESS: "GET_REGIONS_SUCCESS",
    GET_REGIONS_FAILURE: "GET_REGIONS_FAILURE",

    PUT_REGIONS: "PUT_REGIONS",
    PUT_REGIONS_SUCCESS: "PUT_REGIONS_SUCCESS",
    PUT_REGIONS_FAILURE: "PUT_REGIONS_FAILURE",

    POST_REGIONS: "POST_REGIONS",
    POST_REGIONS_SUCCESS: "POST_REGIONS_SUCCESS",
    POST_REGIONS_FAILURE: "POST_REGIONS_FAILURE",

    DELETE_REGIONS: "DELETE_REGIONS",
    DELETE_REGIONS_SUCCESS: "DELETE_REGIONS_SUCCESS",
    DELETE_REGIONS_FAILURE: "DELETE_REGIONS_FAILURE",
};
