export default {
    FETCH_ROUTES: "FETCH_ROUTES",
    FETCH_ROUTES_SUCCESS: "FETCH_ROUTES_SUCCESS",
    FETCH_ROUTES_FAILURE: "FETCH_ROUTES_FAILURE",

    GET_ROUTES: "GET_ROUTES",
    GET_ROUTES_SUCCESS: "GET_ROUTES_SUCCESS",
    GET_ROUTES_FAILURE: "GET_ROUTES_FAILURE",

    PUT_ROUTES: "PUT_ROUTES",
    PUT_ROUTES_SUCCESS: "PUT_ROUTES_SUCCESS",
    PUT_ROUTES_FAILURE: "PUT_ROUTES_FAILURE",

    POST_ROUTES: "POST_ROUTES",
    POST_ROUTES_SUCCESS: "POST_ROUTES_SUCCESS",
    POST_ROUTES_FAILURE: "POST_ROUTES_FAILURE",

    DELETE_ROUTES: "DELETE_ROUTES",
    DELETE_ROUTES_SUCCESS: "DELETE_ROUTES_SUCCESS",
    DELETE_ROUTES_FAILURE: "DELETE_ROUTES_FAILURE",

    DELETE_ROUTE: "DELETE_ROUTE",
    DELETE_ROUTE_SUCCESS: "DELETE_ROUTE_SUCCESS",
    DELETE_ROUTE_FAILURE: "DELETE_ROUTE_FAILURE",

    CHANGE_NAME_ROUTES: "CHANGE_NAME_ROUTES_ROUTES",
    CHANGE_NAME_ROUTES_SUCCESS: "CHANGE_NAME_ROUTES_ROUTES_SUCCESS",
    CHANGE_NAME_ROUTES_FAILURE: "CHANGE_NAME_ROUTES_ROUTES_FAILURE",

    CLONE_ROUTES: "CLONE_ROUTES",
    CLONE_ROUTES_SUCCESS: "CLONE_ROUTES_SUCCESS",
    CLONE_ROUTES_FAILURE: "CLONE_ROUTES_FAILURE",

    PUBLISH_ROUTES: "PUBLISH_ROUTES",
    PUBLISH_ROUTES_SUCCESS: "PUBLISH_ROUTES_SUCCESS",
    PUBLISH_ROUTES_FAILURE: "PUBLISH_ROUTES_FAILURE",

    UNPUBLISH_ROUTES: "UNPUBLISH_ROUTES",
    UNPUBLISH_ROUTES_SUCCESS: "UNPUBLISH_ROUTES_SUCCESS",
    UNPUBLISH_ROUTES_FAILURE: "UNPUBLISH_ROUTES_FAILURE",
};
