export const RoutesStatisticsConstants = {
    GET_ROUTES_STATISTICS: "GET_ROUTES_STATISTICS",
    GET_ROUTES_STATISTICS_SUCCESS: "GET_ROUTES_STATISTICS_SUCCESS",
    GET_ROUTES_STATISTICS_FAILURE: "GET_ROUTES_STATISTICS_FAILURE",

    GET_ROUTES_STATISTICS_BY_VERSION: "GET_ROUTES_STATISTICS_BY_VERSION",
    GET_ROUTES_STATISTICS_BY_VERSION_SUCCESS: "GET_ROUTES_STATISTICS_BY_VERSION_SUCCESS",
    GET_ROUTES_STATISTICS_BY_VERSION_FAILURE: "GET_ROUTES_STATISTICS_BY_VERSION_FAILURE",
};
