export const RoutesEventsConstants = {
    PUT_ROUTES_EVENTS: "PUT_ROUTES_EVENTS",
    PUT_ROUTES_EVENTS_SUCCESS: "PUT_ROUTES_EVENTS_SUCCESS",
    PUT_ROUTES_EVENTS_FAILURE: "PUT_ROUTES_EVENTS_FAILURE",
};
