export const RoutesWindowsConstants = {
    FETCH_ROUTES_WINDOWS: "FETCH_ROUTES_WINDOWS",
    FETCH_ROUTES_WINDOWS_SUCCESS: "FETCH_ROUTES_WINDOWS_SUCCESS",
    FETCH_ROUTES_WINDOWS_FAILURE: "FETCH_ROUTES_WINDOWS_FAILURE",

    GET_ROUTES_WINDOWS: "GET_ROUTES_WINDOWS",
    GET_ROUTES_WINDOWS_SUCCESS: "GET_ROUTES_WINDOWS_SUCCESS",
    GET_ROUTES_WINDOWS_FAILURE: "GET_ROUTES_WINDOWS_FAILURE",

    GET_ROUTES_WINDOWS_IN_PROGRESS: "GET_ROUTES_WINDOWS_IN_PROGRESS",
    GET_ROUTES_WINDOWS_IN_PROGRESS_SUCCESS: "GET_ROUTES_WINDOWS_IN_PROGRESS_SUCCESS",
    GET_ROUTES_WINDOWS_IN_PROGRESS_FAILURE: "GET_ROUTES_WINDOWS_IN_PROGRESS_FAILURE",

    PUT_ROUTES_WINDOWS: "PUT_ROUTES_WINDOWS",
    PUT_ROUTES_WINDOWS_SUCCESS: "PUT_ROUTES_WINDOWS_SUCCESS",
    PUT_ROUTES_WINDOWS_FAILURE: "PUT_ROUTES_WINDOWS_FAILURE",

    POST_ROUTES_WINDOWS: "POST_ROUTES_WINDOWS",
    POST_ROUTES_WINDOWS_SUCCESS: "POST_ROUTES_WINDOWS_SUCCESS",
    POST_ROUTES_WINDOWS_FAILURE: "POST_ROUTES_WINDOWS_FAILURE",

    DELETE_ROUTES_WINDOWS: "DELETE_ROUTES_WINDOWS",
    DELETE_ROUTES_WINDOWS_SUCCESS: "DELETE_ROUTES_WINDOWS_SUCCESS",
    DELETE_ROUTES_WINDOWS_FAILURE: "DELETE_ROUTES_WINDOWS_FAILURE",

    GET_ROUTES_WINDOWS_CONFLICTS: "GET_ROUTES_WINDOWS_CONFLICTS",
    GET_ROUTES_WINDOWS_CONFLICTS_SUCCESS: "GET_ROUTES_WINDOWS_CONFLICTS_SUCCESS",
    GET_ROUTES_WINDOWS_CONFLICTS_FAILURE: "GET_ROUTES_WINDOWS_CONFLICTS_FAILURE",

    GET_ROUTES_WINDOWS_ZONE: "GET_ROUTES_WINDOWS_ZONE",
    GET_ROUTES_WINDOWS_ZONE_SUCCESS: "GET_ROUTES_WINDOWS_ZONE_SUCCESS",
    GET_ROUTES_WINDOWS_ZONE_FAILURE: "GET_ROUTES_WINDOWS_ZONE_FAILURE",

    PUT_ROUTES_WINDOWS_DETAILS: "PUT_ROUTES_WINDOWS_DETAILS",
    PUT_ROUTES_WINDOWS_DETAILS_SUCCESS: "PUT_ROUTES_WINDOWS_DETAILS_SUCCESS",
    PUT_ROUTES_WINDOWS_DETAILS_FAILURE: "PUT_ROUTES_WINDOWS_DETAILS_FAILURE",

    GET_ROUTES_WINDOWS_SUBMIT: "GET_ROUTES_WINDOWS_SUBMIT",
    GET_ROUTES_WINDOWS_SUBMIT_SUCCESS: "GET_ROUTES_WINDOWS_SUBMIT_SUCCESS",
    GET_ROUTES_WINDOWS_SUBMIT_FAILURE: "GET_ROUTES_WINDOWS_SUBMIT_FAILURE",

    GET_ROUTES_WINDOWS_PARAM: "GET_ROUTES_WINDOWS_PARAM",
    GET_ROUTES_WINDOWS_PARAM_SUCCESS: "GET_ROUTES_WINDOWS_PARAM_SUCCESS",
    GET_ROUTES_WINDOWS_PARAM_FAILURE: "GET_ROUTES_WINDOWS_PARAM_FAILURE",

    GET_ROUTES_WINDOWS_SUB: "GET_ROUTES_WINDOWS_SUB",
    GET_ROUTES_WINDOWS_SUB_SUCCESS: "GET_ROUTES_WINDOWS_SUB_SUCCESS",
    GET_ROUTES_WINDOWS_SUB_FAILURE: "GET_ROUTES_WINDOWS_SUB_FAILURE",

    GET_ROUTES_WINDOWS_FINISH: "GET_ROUTES_WINDOWS_FINISH",
    GET_ROUTES_WINDOWS_FINISH_SUCCESS: "GET_ROUTES_WINDOWS_FINISH_SUCCESS",
    GET_ROUTES_WINDOWS_FINISH_FAILURE: "GET_ROUTES_WINDOWS_FINISH_FAILURE",

    GET_APPROVED_ORIGINALS: "GET_APPROVED_ORIGINALS",
    GET_APPROVED_ORIGINALS_SUCCESS: "GET_APPROVED_ORIGINALS_SUCCESS",
    GET_APPROVED_ORIGINALS_FAILURE: "GET_APPROVED_ORIGINALS_FAILURE"
};
