export const RoutesMarkersConstants = {
    POST_ROUTES_MARKERS: "POST_ROUTES_MARKERS",
    POST_ROUTES_MARKERS_SUCCESS: "POST_ROUTES_MARKERS_SUCCESS",
    POST_ROUTES_MARKERS_FAILURE: "POST_ROUTES_MARKERS_FAILURE",
};
