export const RoutesVersionEventsConstants = {
    FETCH_ROUTES_VERSION_EVENTS: "FETCH_ROUTES_VERSION_EVENTS",
    FETCH_ROUTES_VERSION_EVENTS_SUCCESS: "FETCH_ROUTES_VERSION_EVENTS_SUCCESS",
    FETCH_ROUTES_VERSION_EVENTS_FAILURE: "FETCH_ROUTES_VERSION_EVENTS_FAILURE",

    GET_ROUTES_VERSION_EVENTS: "GET_ROUTES_VERSION_EVENTS",
    GET_ROUTES_VERSION_EVENTS_SUCCESS: "GET_ROUTES_VERSION_EVENTS_SUCCESS",
    GET_ROUTES_VERSION_EVENTS_FAILURE: "GET_ROUTES_VERSION_EVENTS_FAILURE",

    PUT_ROUTES_VERSION_EVENTS: "PUT_ROUTES_VERSION_EVENTS",
    PUT_ROUTES_VERSION_EVENTS_SUCCESS: "PUT_ROUTES_VERSION_EVENTS_SUCCESS",
    PUT_ROUTES_VERSION_EVENTS_FAILURE: "PUT_ROUTES_VERSION_EVENTS_FAILURE",

    POST_ROUTES_VERSION_EVENTS: "POST_ROUTES_VERSION_EVENTS",
    POST_ROUTES_VERSION_EVENTS_SUCCESS: "POST_ROUTES_VERSION_EVENTS_SUCCESS",
    POST_ROUTES_VERSION_EVENTS_FAILURE: "POST_ROUTES_VERSION_EVENTS_FAILURE",

    DELETE_ROUTES_VERSION_EVENTS: "DELETE_ROUTES_VERSION_EVENTS",
    DELETE_ROUTES_VERSION_EVENTS_SUCCESS: "DELETE_ROUTES_VERSION_EVENTS_SUCCESS",
    DELETE_ROUTES_VERSION_EVENTS_FAILURE: "DELETE_ROUTES_VERSION_EVENTS_FAILURE",

    FETCH_ROUTES_VERSION_STORES: "FETCH_ROUTES_VERSION_STORES",
    FETCH_ROUTES_VERSION_STORES_SUCCESS: "FETCH_ROUTES_VERSION_STORES_SUCCESS",
    FETCH_ROUTES_VERSION_STORES_FAILURE: "FETCH_ROUTES_VERSION_STORES_FAILURE",

    CONFLICTS_ROUTES_VERSION: "CONFLICTS_ROUTES_VERSION",
    CONFLICTS_ROUTES_VERSION_SUCCESS: "CONFLICTS_ROUTES_VERSION_SUCCESS",
    CONFLICTS_ROUTES_VERSION_FAILURE: "CONFLICTS_ROUTES_VERSION_FAILURE",

    FETCH_ROUTES_VERSION_EVENTS_PARENTS: "FETCH_ROUTES_VERSION_EVENTS_PARENTS",
    FETCH_ROUTES_VERSION_EVENTS_PARENTS_SUCCESS: "FETCH_ROUTES_VERSION_EVENTS_PARENTS_SUCCESS",
    FETCH_ROUTES_VERSION_EVENTS_PARENTS_FAILURE: "FETCH_ROUTES_VERSION_EVENTS_PARENTS_FAILURE",

    DELETE_ROUTES_VERSION_EVENTS_DATES : "DELETE_ROUTES_VERSION_EVENTS_DATES",
    DELETE_ROUTES_VERSION_EVENTS_DATES_SUCCESS: "DELETE_ROUTES_VERSION_EVENTS_DATES_SUCCESS",
    DELETE_ROUTES_VERSION_EVENTS_DATES_FAILURE: "DELETE_ROUTES_VERSION_EVENTS_DATES_FAILURE"
};
