export const RoutesVersionsConstants = {
    GET_ROUTES_VERSIONS: "GET_ROUTES_VERSIONS",
    GET_ROUTES_VERSIONS_SUCCESS: "GET_ROUTES_VERSIONS_SUCCESS",
    GET_ROUTES_VERSIONS_FAILURE: "GET_ROUTES_VERSIONS_FAILURE",

    POST_ROUTES_VERSIONS: "POST_ROUTES_VERSIONS",
    POST_ROUTES_VERSIONS_SUCCESS: "POST_ROUTES_VERSIONS_SUCCESS",
    POST_ROUTES_VERSIONS_FAILURE: "POST_ROUTES_VERSIONS_FAILURE",

    PUT_ROUTES_VERSIONS: "PUT_ROUTES_VERSIONS",
    PUT_ROUTES_VERSIONS_SUCCESS: "PUT_ROUTES_VERSIONS_SUCCESS",
    PUT_ROUTES_VERSIONS_FAILURE: "PUT_ROUTES_VERSIONS_FAILURE",

    DELETE_ROUTES_VERSIONS: "DELETE_ROUTES_VERSIONS",
    DELETE_ROUTES_VERSIONS_SUCCESS: "DELETE_ROUTES_VERSIONS_SUCCESS",
    DELETE_ROUTES_VERSIONS_FAILURE: "DELETE_ROUTES_VERSIONS_FAILURE",

    CLEAR_ROUTES_VERSIONS: "CLEAR_ROUTES_VERSIONS",
    CLEAR_ROUTES_VERSIONS_SUCCESS: "CLEAR_ROUTES_VERSIONS_SUCCESS",
    CLEAR_ROUTES_VERSIONS_FAILURE: "CLEAR_ROUTES_VERSIONS_FAILURE",

    PERSIST_ROUTES_VERSIONS: "PERSIST_ROUTES_VERSIONS",
    PERSIST_ROUTES_VERSIONS_SUCCESS: "PERSIST_ROUTES_VERSIONS_SUCCESS",
    PERSIST_ROUTES_VERSIONS_FAILURE: "PERSIST_ROUTES_VERSIONS_FAILURE",
};
