export const RoutesWindowMessageConstants = {
    FETCH_ROUTES_WINDOW_MESSAGE: "FETCH_ROUTES_WINDOW_MESSAGE",
    FETCH_ROUTES_WINDOW_MESSAGE_SUCCESS: "FETCH_ROUTES_WINDOW_MESSAGE_SUCCESS",
    FETCH_ROUTES_WINDOW_MESSAGE_FAILURE: "FETCH_ROUTES_WINDOW_MESSAGE_FAILURE",

    GET_ROUTES_WINDOW_MESSAGE_UNREAD: "GET_ROUTES_WINDOW_MESSAGE_UNREAD",
    GET_ROUTES_WINDOW_MESSAGE_UNREAD_SUCCESS: "GET_ROUTES_WINDOW_MESSAGE_UNREAD_SUCCESS",
    GET_ROUTES_WINDOW_MESSAGE_UNREAD_FAILURE: "GET_ROUTES_WINDOW_MESSAGE_UNREAD_FAILURE",

    POST_ROUTES_WINDOW_MESSAGE: "POST_ROUTES_WINDOW_MESSAGE",
    POST_ROUTES_WINDOW_MESSAGE_SUCCESS: "POST_ROUTES_WINDOW_MESSAGE_SUCCESS",
    POST_ROUTES_WINDOW_MESSAGE_FAILURE: "POST_ROUTES_WINDOW_MESSAGE_FAILURE",

};
