export const RoutesRatesConstants = {
    FETCH_ROUTES_RATES: "FETCH_ROUTES_RATES",
    FETCH_ROUTES_RATES_SUCCESS: "FETCH_ROUTES_RATES_SUCCESS",
    FETCH_ROUTES_RATES_FAILURE: "FETCH_ROUTES_RATES_FAILURE",

    GET_ROUTES_RATES: "GET_ROUTES_RATES",
    GET_ROUTES_RATES_SUCCESS: "GET_ROUTES_RATES_SUCCESS",
    GET_ROUTES_RATES_FAILURE: "GET_ROUTES_RATES_FAILURE",

    PUT_ROUTES_RATES: "PUT_ROUTES_RATES",
    PUT_ROUTES_RATES_SUCCESS: "PUT_ROUTES_RATES_SUCCESS",
    PUT_ROUTES_RATES_FAILURE: "PUT_ROUTES_RATES_FAILURE",

    POST_ROUTES_RATES: "POST_ROUTES_RATES",
    POST_ROUTES_RATES_SUCCESS: "POST_ROUTES_RATES_SUCCESS",
    POST_ROUTES_RATES_FAILURE: "POST_ROUTES_RATES_FAILURE",

    DELETE_ROUTES_RATES: "DELETE_ROUTES_RATES",
    DELETE_ROUTES_RATES_SUCCESS: "DELETE_ROUTES_RATES_SUCCESS",
    DELETE_ROUTES_RATES_FAILURE: "DELETE_ROUTES_RATES_FAILURE",
};
