export default
{
    FETCH_STORES: "FETCH_STORES",
    FETCH_STORES_SUCCESS: "FETCH_STORES_SUCCESS",
    FETCH_STORES_FAILURE: "FETCH_STORES_FAILURE",

    FETCH_STORES_ATTENDANCES: "FETCH_STORES_ATTENDANCES",
    FETCH_STORES_ATTENDANCES_SUCCESS: "FETCH_STORES_ATTENDANCES_SUCCESS",
    FETCH_STORES_ATTENDANCES_FAILURE: "FETCH_STORES_ATTENDANCES_FAILURE",

    FETCH_STORES_BILLINGS: "FETCH_STORES_BILLINGS",
    FETCH_STORES_BILLINGS_SUCCESS: "FETCH_STORES_BILLINGS_SUCCESS",
    FETCH_STORES_BILLINGS_FAILURE: "FETCH_STORES_BILLINGS_FAILURE",

    GET_STORES: "GET_STORES",
    GET_STORES_SUCCESS: "GET_STORES_SUCCESS",
    GET_STORES_FAILURE: "GET_STORES_FAILURE",

    PUT_STORES: "PUT_STORES",
    PUT_STORES_SUCCESS: "PUT_STORES_SUCCESS",
    PUT_STORES_FAILURE: "PUT_STORES_FAILURE",

    POST_STORES: "POST_STORES",
    POST_STORES_SUCCESS: "POST_STORES_SUCCESS",
    POST_STORES_FAILURE: "POST_STORES_FAILURE",

    DELETE_STORES: "DELETE_STORES",
    DELETE_STORES_SUCCESS: "DELETE_STORES_SUCCESS",
    DELETE_STORES_FAILURE: "DELETE_STORES_FAILURE",
}
