export default {
    FETCH_TASKS: "FETCH_TASKS",
    FETCH_TASKS_SUCCESS: "FETCH_TASKS_SUCCESS",
    FETCH_TASKS_FAILURE: "FETCH_TASKS_FAILURE",

    GET_TASK: "GET_TASK",
    GET_TASK_SUCCESS: "GET_TASK_SUCCESS",
    GET_TASK_FAILURE: "GET_TASK_FAILURE",

    PUT_TASK: "PUT_TASK",
    PUT_TASK_SUCCESS: "PUT_TASK_SUCCESS",
    PUT_TASK_FAILURE: "PUT_TASK_FAILURE",

    POST_TASK: "POST_TASK",
    POST_TASK_SUCCESS: "POST_TASK_SUCCESS",
    POST_TASK_FAILURE: "POST_TASK_FAILURE",

    DELETE_TASK: "DELETE_TASK",
    DELETE_TASK_SUCCESS: "DELETE_TASK_SUCCESS",
    DELETE_TASK_FAILURE: "DELETE_TASK_FAILURE",
};