export const TimezoneConstants = {
    FETCH_TIMEZONE: "FETCH_TIMEZONE",
    FETCH_TIMEZONE_SUCCESS: "FETCH_TIMEZONE_SUCCESS",
    FETCH_TIMEZONE_FAILURE: "FETCH_TIMEZONE_FAILURE",

    GET_TIMEZONE: "GET_TIMEZONE",
    GET_TIMEZONE_SUCCESS: "GET_TIMEZONE_SUCCESS",
    GET_TIMEZONE_FAILURE: "GET_TIMEZONE_FAILURE",

    PUT_TIMEZONE: "PUT_TIMEZONE",
    PUT_TIMEZONE_SUCCESS: "PUT_TIMEZONE_SUCCESS",
    PUT_TIMEZONE_FAILURE: "PUT_TIMEZONE_FAILURE",

    POST_TIMEZONE: "POST_TIMEZONE",
    POST_TIMEZONE_SUCCESS: "POST_TIMEZONE_SUCCESS",
    POST_TIMEZONE_FAILURE: "POST_TIMEZONE_FAILURE",

    DELETE_TIMEZONE: "DELETE_TIMEZONE",
    DELETE_TIMEZONE_SUCCESS: "DELETE_TIMEZONE_SUCCESS",
    DELETE_TIMEZONE_FAILURE: "DELETE_TIMEZONE_FAILURE",
};