export const UsersConstants = {
    USER_LOGIN: "USER_LOGIN",
    USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
    USER_LOGIN_FAILURE: "USER_HIERARCHY_FAILURE",
    USER_LOGIN_CLEAR: "USER_LOGIN_CLEAR",

    USER_INACTIVATIONS: "USER_INACTIVATIONS",
    USER_INACTIVATIONS_SUCCESS: "USER_INACTIVATIONS_SUCCESS",
    USER_INACTIVATIONS_FAILURE: "USER_INACTIVATIONS_FAILURE",

    USER_PROFILE: "USER_PROFILE",
    USER_PROFILE_SUCCESS: "USER_PROFILE_SUCCESS",
    USER_PROFILE_FAILURE: "USER_PROFILE_FAILURE",

    FETCH_USERS: "FETCH_USERS",
    FETCH_USERS_SUCCESS: "FETCH_USERS_SUCCESS",
    FETCH_USERS_FAILURE: "FETCH_USERS_FAILURE",

    GET_USERS: "GET_USERS",
    GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
    GET_USERS_FAILURE: "GET_USERS_FAILURE",

    USER_POST_CONTRACTOR: 'USER_POST_CONTRACTOR',
    USER_POST_CONTRACTOR_SUCCESS: 'USER_POST_CONTRACTOR_SUCCESS',
    USER_POST_CONTRACTOR_FAILURE: 'USER_POST_CONTRACTOR_FAILURE'
};
