export const WithoutRouteConstants = {
    FETCH_WITHOUT_ROUTE: "FETCH_WITHOUT_ROUTE",
    FETCH_WITHOUT_ROUTE_SUCCESS: "FETCH_WITHOUT_ROUTE_SUCCESS",
    FETCH_WITHOUT_ROUTE_FAILURE: "FETCH_WITHOUT_ROUTE_FAILURE",
};