export const ZonesConstants = {
    FIND_ZONES: "FIND_ZONES",
    FIND_ZONES_SUCCESS: "FIND_ZONES_SUCCESS",
    FIND_ZONES_FAILURE: "FIND_ZONES_FAILURE",

    FETCH_ZONES: "FETCH_ZONES",
    FETCH_ZONES_SUCCESS: "FETCH_ZONES_SUCCESS",
    FETCH_ZONES_FAILURE: "FETCH_ZONES_FAILURE",

    GET_ZONES: "GET_ZONES",
    GET_ZONES_SUCCESS: "GET_ZONES_SUCCESS",
    GET_ZONES_FAILURE: "GET_ZONES_FAILURE",

    PUT_ZONES: "PUT_ZONES",
    PUT_ZONES_SUCCESS: "PUT_ZONES_SUCCESS",
    PUT_ZONES_FAILURE: "PUT_ZONES_FAILURE",

    POST_ZONES: "POST_ZONES",
    POST_ZONES_SUCCESS: "POST_ZONES_SUCCESS",
    POST_ZONES_FAILURE: "POST_ZONES_FAILURE",

    DELETE_ZONES: "DELETE_ZONES",
    DELETE_ZONES_SUCCESS: "DELETE_ZONES_SUCCESS",
    DELETE_ZONES_FAILURE: "DELETE_ZONES_FAILURE",

};
