export const MANAGER_TIME_TYPES = {
  FETCH_MANAGER_TIME_REQUEST: 'FETCH_MANAGER_TIME_REQUEST',
  FETCH_MANAGER_TIME_SUCESS: 'FETCH_MANAGER_TIME_SUCCESS',
  FETCH_MANAGER_TIME_FAILURE: 'FETCH_MANAGER_TIME_FAILURE',
}
