export const FLAG_NETWORK = {
  FETCH_GROUPS_REQUEST: 'FETCH_GROUPS_REQUEST',
  FETCH_GROUPS_SUCCESS: 'FETCH_GROUPS_SUCCESS',
  FETCH_GROUPS_FAILURE: 'FETCH_GROUPS_FAILURE',
  ADD_FLAG_FILTER: 'ADD_FLAG_FILTER',
  REMOVE_ALL_FLAG_FILTERS: 'REMOVE_ALL_FLAG_FILTERS',
  REMOVE_FLAG_ITEM: 'REMOVE_FLAG_ITEM',

  FETCH_FLAG_BY_QUERY_PARAM_REQUEST: 'FETCH_FLAG_BY_QUERY_PARAM_REQUEST',
  FETCH_FLAG_BY_QUERY_PARAM_SUCCESS: 'FETCH_FLAG_BY_QUERY_PARAM_SUCCESS',
  FETCH_FLAG_BY_QUERY_PARAM_FAILURE: 'FETCH_FLAG_BY_QUERY_PARAM_FAILURE',
}
