export const SERVICE_POINT_TYPES = {
  FETCH_SERVICE_POINT_REQUEST: 'FETCH_SERVICE_POINT_REQUEST',
  FETCH_SERVICE_POINT_SUCCESS: 'FETCH_SERVICE_POINT_SUCCESS',
  FETCH_SERVICE_POINT_FAILURE: 'FETCH_SERVICE_POINT_FAILURE',
}
