export const GROUP_TYPES = {
  FETCH_GROUP_REQUEST: 'FETCH_GROUP_REQUEST',
  FETCH_GROUP_SUCCESS: 'FETCH_GROUP_SUCCESS',
  FETCH_GROUP_FAILURE: 'FETCH_GROUP_FAILURE',
  ADD_GROUP_FILTER: 'ADD_GROUP_FILTER',
  REMOVE_ALL_GROUP_FILTERS: 'REMOVE_ALL_FILTERS',
  REMOVE_GROUP_ITEM: 'REMOVE_ITEM',

  FETCH_GROUP_BY_QUERY_PARAM_REQUEST: 'FETCH_GROUP_BY_QUERY_PARAM_REQUEST',
  FETCH_GROUP_BY_QUERY_PARAM_SUCCESS: 'FETCH_GROUP_BY_QUERY_PARAM_SUCCESS',
  FETCH_GROUP_BY_QUERY_PARAM_FAILURE: 'FETCH_GROUP_BY_QUERY_PARAM_FAILURE',
}
