export const NETWORK_TYPES = {
  FETCH_NETWORK_REQUEST: 'FETCH_NETWORK_REQUEST',
  FETCH_NETWORK_SUCCESS: 'FETCH_NETWORK_SUCCESS',
  FETCH_NETWORK_FAILURE: 'FETCH_NETWORK_FAILURE',
  ADD_NETWORK_FILTER: 'ADD_NETWORK_FILTER',
  REMOVE_ALL_NETWORK_FILTERS: 'REMOVE_ALL_NETWORK_FILTERS',
  REMOVE_NETWORK_ITEM: 'REMOVE_NETWORK_ITEM',

  FETCH_NETWORK_BY_QUERY_PARAM_REQUEST: 'FETCH_NETWORK_BY_QUERY_PARAM_REQUEST',
  FETCH_NETWORK_BY_QUERY_PARAM_SUCCESS: 'FETCH_NETWORK_BY_QUERY_PARAM_SUCCESS',
  FETCH_NETWORK_BY_QUERY_PARAM_FAILURE: 'FETCH_NETWORK_BY_QUERY_PARAM_FAILURE',
}
