export { Avatar } from '../../../../../components/form/sections'
export * from '../../../components'
export { default as BasicData } from './BasicData'
export { default as FormDefinition } from './FormDefinition'
export { default as LicenseControl } from './LicenseControl'
export { default as PPTTemplate } from './PPTTemplate'
export { default as ResponsibleAdministrator } from './ResponsibleAdministrator'
export { default as Status } from './Status'
export { default as Terms } from './Terms'
