export const ADDRESS_TYPE_MAP = {
  AREA: 'Área',
  ACESSO: 'Acesso',
  AEROPORTO: 'Aeroporto',
  ALAMEDA: 'Alameda',
  AVENIDA: 'Avenida',
  CAMPO: 'Campo',
  CHACARA: 'Chácara',
  COLONIA: 'Colônia',
  CONDOMINIO: 'Condomínio',
  CONJUNTO: 'Conjunto',
  DISTRITO: 'Distrito',
  ESPLANADA: 'Esplanada',
  ESTACAO: 'Estação',
  ESTRADA: 'Estrada',
  FAVELA: 'Favela',
  FAZENDA: 'Fazenda',
  FEIRA: 'Feira',
  JARDIM: 'Jardim',
  LADEIRA: 'Ladeira',
  LAGO: 'Lago',
  LAGOA: 'Lagoa',
  LARGO: 'Largo',
  LOTEAMENTO: 'Loteamento',
  MORRO: 'Morro',
  NUCLEO: 'Núcleo',
  PATIO: 'Pátio',
  PARQUE: 'Parque',
  PASSARELA: 'Passarela',
  PRACA: 'Praça',
  PRAIA: 'Praia',
  QUADRA: 'Quadra',
  RECANTO: 'Recanto',
  RESIDENCIAL: 'Residencial',
  RODOVIA: 'Rodovia',
  RUA: 'Rua',
  SITIO: 'Sítio',
  SETOR: 'Setor',
  TRAVESSA: 'Travessa',
  TRECHO: 'Trecho',
  TREVO: 'Trevo',
  VALE: 'Vale',
  VEREDA: 'Vereda',
  VIA: 'Via',
  VIADUTO: 'Viaduto',
  VIELA: 'Viela',
  VILA: 'Vila',
  OUTROS: 'Outros',
} as const

export type AddressType =
  (typeof ADDRESS_TYPE_MAP)[keyof typeof ADDRESS_TYPE_MAP]

const addressType = Object.values(ADDRESS_TYPE_MAP)

export default addressType
