export const DEFINE_FUNCTION_TYPES = {
  FETCH_ALL_FUNCTION_REQUEST: 'FETCH_ALL_FUNCTION_REQUEST',
  FETCH_ALL_FUNCTION_SUCCESS: 'FETCH_ALL_FUNCTION_SUCCESS',
  FETCH_ALL_FUNCTION_FAILURE: 'FETCH_ALL_FUNCTION_FAILURE',
}
