export const GET_OCCUPATION_REQUEST = 'GET_OCCUPATION_REQUEST'
export const GET_OCCUPATION_SUCESS = 'GET_OCCUPATION_SUCESS'
export const GET_OCCUPATION_FAILURE = 'GET_OCCUPATION_FAILURE'

export const POST_OCCUPATION_FILTER = 'POST_OCCUPATION_FILTER'
