export const WIDGET14_SUCESS = 'WIDGET14_SUCESS'
export const WIDGET14_REQUEST = 'WIDGET14_REQUEST'
export const WIDGET14_FAILURE = 'WIDGET14_FAILURE'

export const WIDGET142_SUCESS = 'WIDGET142_SUCESS'
export const WIDGET142_REQUEST = 'WIDGET142_REQUEST'
export const WIDGET142_FAILURE = 'WIDGET142_FAILURE'



export const WIDGET15_SUCESS = 'WIDGET15_SUCESS'
export const WIDGET15_REQUEST = 'WIDGET15_REQUEST'
export const WIDGET15_FAILURE = 'WIDGET15_FAILURE'


export const WIDGET16_REQUEST = 'WIDGET16_REQUEST'
export const WIDGET16_SUCESS  = 'WIDGET16_SUCESS'
export const WIDGET16_FAILURE = 'WIDGET16_FAILURE'


export const WIDGET17_SUCESS =  'WIDGET17_SUCESS'
export const WIDGET17_REQUEST = 'WIDGET17_REQUEST'
export const WIDGET17_FAILURE = 'WIDGET17_FAILURE'


export const WIDGET18_REQUEST = 'WIDGET18_REQUEST'
export const WIDGET18_SUCESS = 'WIDGET18_SUCESS'
export const WIDGET18_FAILURE = 'WIDGET18_FAILURE'


export const WIDGET19_REQUEST = 'WIDGET19_REQUEST'
export const WIDGET19_SUCESS = 'WIDGET19_SUCESS'
export const WIDGET19_FAILURE = ' WIDGET19_FAILURE'


export const WIDGET20_REQUEST = 'WIDGET20_REQUEST'
export const WIDGET20_SUCESS =  'WIDGET20_SUCESS'
export const WIDGET20_FAILURE = 'WIDGET20_FAILURE'


export const WIDGET21_REQUEST = 'WIDGET21_REQUEST'
export const WIDGET21_SUCESS =  'WIDGET21_SUCESS'
export const WIDGET21_FAILURE = 'WIDGET21_FAILURE'


export const WIDGET22_REQUEST = 'WIDGET22_REQUEST'
export const WIDGET22_SUCESS = 'WIDGET22_SUCESS'
export const WIDGET22_FAILURE = 'WIDGET22_FAILURE'



export const WIDGET23_SUCESS = 'WIDGET23_SUCESS'
export const WIDGET23_REQUEST = 'WIDGET23_REQUEST'
export const WIDGET23_FAILURE = 'WIDGET23_FAILURE'


export const WIDGET232_SUCESS = 'WIDGET232_SUCESS'
export const WIDGET232_REQUEST = 'WIDGET232_REQUEST'
export const WIDGET232_FAILURE = 'WIDGET232_FAILURE'

export const WIDGET24_SUCESS = 'WIDGET24_SUCESS'
export const WIDGET24_REQUEST = 'WIDGET24_REQUEST'
export const WIDGET24_FAILURE = 'WIDGET24_FAILURE'


export const WIDGET25_SUCESS = 'WIDGET25_SUCESS'
export const WIDGET25_REQUEST = 'WIDGET25_REQUEST'
export const WIDGET25_FAILURE = 'WIDGET25_FAILURE'


export const WIDGET26_SUCESS = 'WIDGET26_SUCESS'
export const WIDGET26_REQUEST = 'WIDGET26_REQUEST'
export const WIDGET26_FAILURE = 'WIDGET26_FAILURE'


export const WIDGET27_SUCESS =  'WIDGET27_SUCESS'
export const WIDGET27_REQUEST = 'WIDGET27_REQUEST'
export const WIDGET27_FAILURE = 'WIDGET27_FAILURE'



export const WIDGET28_SUCESS =  'WIDGET28_SUCESS'
export const WIDGET28_REQUEST = 'WIDGET28_REQUEST'
export const WIDGET28_FAILURE = 'WIDGET28_FAILURE'





export const WIDGET29_SUCESS = 'WIDGET29_SUCESS'
export const WIDGET29_REQUEST = 'WIDGET29_REQUEST'
export const WIDGET29_FAILURE = 'WIDGET29_FAILURE'



export const WIDGET30_SUCESS = ' WIDGET30_SUCESS'
export const WIDGET30_REQUEST = 'WIDGET30_REQUEST'
export const WIDGET30_FAILURE = 'WIDGET30_FAILURE'



export const WIDGET31_SUCESS = 'WIDGET31_SUCESS'
export const WIDGET31_REQUEST = 'WIDGET31_REQUEST'
export const WIDGET31_FAILURE = 'WIDGET31_FAILURE'



export const WIDGET32_SUCESS = 'LOADING_SUCESS'
export const WIDGET32_REQUEST = 'LOADING_REQUEST'
export const WIDGET32_FAILURE = 'LOADING_FAILURE'



export const WIDGET33_SUCESS = 'WIDGET33_SUCESS'
export const WIDGET33_REQUEST = 'WIDGET33_REQUEST'
export const WIDGET33_FAILURE = 'WIDGET33_FAILURE'

export const PROGRESS_BAR = 'PROGRESS_BAR'
