export const WIDGET_TYPES = {
  FETCH_WIDGET13_REQUEST: 'FETCH_WIDGET13_REQUEST',
  FETCH_WIDGET13_SUCCESS: 'FECTH_WIDGET13_SUCCESS',
  FETCH_WIDGET13_FAILURE: 'FETCH_WIDGET13_FAILURE',

  FETCH_WIDGET14_REQUEST: 'FETCH_WIDGET14_REQUEST',
  FETCH_WIDGET14_SUCCESS: 'FETCH_WIDGET14_SUCCESS',
  FETCH_WIDGET14_FAILURE: 'FETCH_WIDGET14_FAILURE',

  FETCH_WIDGET15_REQUEST: 'FETCH_WIDGET15_REQUEST',
  FETCH_WIDGET15_SUCCESS: 'FETCH_WIDGET15_SUCCESS',
  FETCH_WIDGET15_FAILURE: 'FETCH_WIDGET15_FAILURE',

  FETCH_WIDGET16_REQUEST: 'FETCH_WIDGET16_REQUEST',
  FETCH_WIDGET16_SUCCESS: 'FETCH_WIDGET16_SUCCESS',
  FETCH_WIDGET16_FAILURE: 'FETCH_WIDGET16_FAILURE',

  FETCH_WIDGET17_REQUEST: 'FETCH_WIDGET17_REQUEST',
  FETCH_WIDGET17_SUCCESS: 'FETCH_WIDGET17_SUCCESS',
  FETCH_WIDGET17_FAILURE: 'FETCH_WIDGET17_FAILURE',

  FETCH_WIDGET18_REQUEST: 'FETCH_WIDGET18_REQUEST',
  FETCH_WIDGET18_SUCCESS: 'FETCH_WIDGET18_SUCCESS',
  FETCH_WIDGET18_FAILURE: 'FETCH_WIDGET18_FAILURE',

  FETCH_WIDGET19_REQUEST: 'FETCH_WIDGET19_REQUEST',
  FETCH_WIDGET19_SUCCESS: 'FETCH_WIDGET19_SUCCESS',
  FETCH_WIDGET19_FAILURE: 'FETCH_WIDGET19_FAILURE',

  FETCH_WIDGET20_REQUEST: 'FETCH_WIDGET20_REQUEST',
  FETCH_WIDGET20_SUCCESS: 'FETCH_WIDGET20_SUCCESS',
  FETCH_WIDGET20_FAILURE: 'FETCH_WIDGET20_FAILURE',

  FETCH_WIDGET21_REQUEST: 'FETCH_WIDGET21_REQUEST',
  FETCH_WIDGET21_SUCCESS: 'FETCH_WIDGET21_SUCCESS',
  FETCH_WIDGET21_FAILURE: 'FETCH_WIDGET21_FAILURE',

  FETCH_WIDGET22_REQUEST: 'FETCH_WIDGET22_REQUEST',
  FETCH_WIDGET22_SUCCESS: 'FETCH_WIDGET22_SUCCESS',
  FETCH_WIDGET22_FAILURE: 'FETCH_WIDGET22_FAILURE',

  FETCH_WIDGET23_REQUEST: 'FETCH_WIDGET23_REQUEST',
  FETCH_WIDGET23_SUCCESS: 'FETCH_WIDGET23_SUCCESS',
  FETCH_WIDGET23_FAILURE: 'FETCH_WIDGET23_FAILURE',

  FETCH_WIDGET24_REQUEST: 'FETCH_WIDGET24_REQUEST',
  FETCH_WIDGET24_SUCCESS: 'FETCH_WIDGET24_SUCCESS',
  FETCH_WIDGET24_FAILURE: 'FETCH_WIDGET24_FAILURE',

  FETCH_WIDGET25_REQUEST: 'FETCH_WIDGET25_REQUEST',
  FETCH_WIDGET25_SUCCESS: 'FETCH_WIDGET25_SUCCESS',
  FETCH_WIDGET25_FAILURE: 'FETCH_WIDGET25_FAILURE',

  FETCH_WIDGET26_REQUEST: 'FETCH_WIDGET26_REQUEST',
  FETCH_WIDGET26_SUCCESS: 'FETCH_WIDGET26_SUCCESS',
  FETCH_WIDGET26_FAILURE: 'FETCH_WIDGET26_FAILURE',

  FETCH_WIDGET27_REQUEST: 'FETCH_WIDGET27_REQUEST',
  FETCH_WIDGET27_SUCCESS: 'FETCH_WIDGET27_SUCCESS',
  FETCH_WIDGET27_FAILURE: 'FETCH_WIDGET27_FAILURE',

  FETCH_WIDGET28_REQUEST: 'FETCH_WIDGET28_REQUEST',
  FETCH_WIDGET28_SUCCESS: 'FETCH_WIDGET28_SUCCESS',
  FETCH_WIDGET28_FAILURE: 'FETCH_WIDGET28_FAILURE',

  FETCH_WIDGET29_REQUEST: 'FETCH_WIDGET29_REQUEST',
  FETCH_WIDGET29_SUCCESS: 'FETCH_WIDGET29___SUCCESS',
  FETCH_WIDGET29_FAILURE: 'FETCH_WIDGET28_FAILURE',

  FETCH_WIDGET30_REQUEST: 'FETCH_WIDGET30_REQUEST',
  FETCH_WIDGET30_SUCCESS: 'FETCH_WIDGET30_SUCCESS',
  FETCH_WIDGET30_FAILURE: 'FETCH_WIDGET30_FAILURE',

  FETCH_WIDGET31_REQUEST: 'FETCH_WIDGET31_REQUEST',
  FETCH_WIDGET31_SUCCESS: 'FETCH_WIDGET31_SUCCESS',
  FETCH_WIDGET31_FAILURE: 'FETCH_WIDGET31_FAILURE',

  FETCH_WIDGET32_REQUEST: 'FETCH_WIDGET32_REQUEST',
  FETCH_WIDGET32_SUCCESS: 'FETCH_WIDGET32_SUCCESS',
  FETCH_WIDGET32_FAILURE: 'FETCH_WIDGET32_FAILURE',

  FETCH_WIDGET33_REQUEST: 'FETCH_WIDGET33_REQUEST',
  FETCH_WIDGET33_SUCCESS: 'FETCH_WIDGET33_SUCCESS',
  FETCH_WIDGET33_FAILURE: 'FETCH_WIDGET33_FAILURE',

  FETCH_WIDGET34_REQUEST: 'FETCH_WIDGET34_REQUEST',
  FETCH_WIDGET34_SUCCESS: 'FETCH_WIDGET34_SUCCESS',
  FETCH_WIDGET34_FAILURE: 'FETCH_WIDGET34_FAILURE',

  FETCH_WIDGET35_REQUEST: 'FETCH_WIDGET35_REQUEST',
  FETCH_WIDGET35_SUCCESS: 'FETCH_WIDGET35_SUCCESS',
  FETCH_WIDGET35_FAILURE: 'FETCH_WIDGET35_FAILURE',

  FETCH_WIDGET36_REQUEST: 'FETCH_WIDGET36_REQUEST',
  FETCH_WIDGET36_SUCCESS: 'FETCH_WIDGET36_SUCCESS',
  FETCH_WIDGET36_FAILURE: 'FETCH_WIDGET36_FAILURE',

  FETCH_WIDGET37_REQUEST: 'FETCH_WIDGET37_REQUEST',
  FETCH_WIDGET37_SUCCESS: 'FETCH_WIDGET37_SUCCESS',
  FETCH_WIDGET37_FAILURE: 'FETCH_WIDGET37_FAILURE',

  FETCH_WIDGET38_REQUEST: 'FETCH_WIDGET38_REQUEST',
  FETCH_WIDGET38_SUCCESS: 'FETCH_WIDGET38_SUCCESS',
  FETCH_WIDGET38_FAILURE: 'FETCH_WIDGET38_FAILURE',

  FETCH_ATTENDENCES_MODAL_REQUEST: 'FETCH_ATTENDENCES_MODAL_REQUEST',
  FETCH_ATTENDENCES_MODAL_SUCCESS: 'FETCH_ATTENDENCES_MODAL_SUCCESS',
  FETCH_ATTENDENCES_MODAL_FAILURE: 'FETCH_ATTENDENCES_MODAL_FAILURE',

  FETCH_DISTRIBUTION_MODAL_REQUEST: 'FETCH_DISTRIBUTION_MODAL_REQUEST',
  FETCH_DISTRIBUTION_MODAL_SUCCESS: 'FETCH_DISTRIBUTION_MODAL_SUCCESS',
  FETCH_DISTRIBUTION_MODAL_FAILURE: 'FETCH_DISTRIBUTION_MODAL_FAILURE',
}
